apiVersion: v1
kind: Service
metadata:
  name: flask-service
  labels:
    app: flask-devops-project
spec:
  selector:
    app: flask-devops-project
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 31200