apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
spec:
  selector:
    matchLabels:
      app: redazayed-devops-project
  replicas: 2 # tells deployment to run 2 pods matching the template
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

  template:
    metadata:
      labels:
        app: redazayed-devops-project
    spec:
      containers:
      - name: redazayed-devops-project
        image: redazayed/udacity-capstone:0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 5000